### PR TITLE
Add support for core and directory overrides of switchres.ini files

### PR DESCRIPTION
**Pull request by Kopert**
_Note: this pull request includes the latest version of https://github.com/antonioginer/switchres as it needs the changes included in https://github.com/antonioginer/switchres/pull/88_

This pull request consists of added code to the method `crt_switch_res_core` of `video_crt_switch.c`. The basis of the functionality is that, whenever there is a **core** change and SR2 is active, and _before_ said change occurs, it re-loads the base switchres.ini file to undo any changes made by a previous override; then it tries to load the core override `.ini` file for the current core, if there is one, then a directory core override.

The base switchres.ini file is re-loaded _only_ if the previous core had overrides. If the user has no override .ini files, then no .ini parsing ever occurs (other than the first one, as it works now).

RetroArch's methods and constants are used to acquire the correct location for the overriding file. On a Linux system, the core override switchres.ini file for the Gambatte core, for example, is searched at `~/.config/retroarch/config/Gambatte/Gambatte.switchres.ini`. This leaves the files next to the .cfg file for core overrides that is already used/supported by RetroArch, only using `.switchres.ini` as the extension instead of `.cfg`.

A similar system is used for directory overrides. For example, the directory overrides for the `Sega - Game Gear` directory, when using the `Genesis Plus GX` core would be searched, on Linux, at `~/.config/retroarch/config/Genesis Plus GX/Sega - Game Gear.switchres.ini`. The justification for directory overrides is that some cores - like Genesis Plus GX - can support multiple different systems such as Game Gear, SMS and Sega Genesis, so having separate settings for those is reasonable in several use cases.

Per-game overrides are not implemented or planned because there is no justification for those that I known of.

Since the base switchres.ini file is loaded before overrides, only variables that are defined differently from this file are taken into account, and the file does not need to be a full configuration. The file contents of `user_mode                 3840x0` are enough to force this super resolution on a core when it is started.

Tests were done by launching different cores with and without overrides, straight from one to the next and also returning to the menu first. All resolution changes occurred as expected with different override values being used whenever they should and the defaults being used on the menu or on a core with no overrides.

This PR also includes a fix to a bug involving pointer comparison, instead of contents, that prevents core changes being detected if the current content is not explicitly closed before starting a new one. The exact line this bug happens is mentioned in the comments below.

No changes are done to menus or to RetroArch's normal overrides functionality.

### CODE REVIEW

**Comment by Kopert** [comment]
Made a change so that .ini (re)loading only happens when the core changes (instead of every resolution change).

**Comment by Kopert** [comment]
New changes:

- The new functionality is isolated on the `video_crt_switch/crt_adjust_sr_ini()` method
- A new check has been added to ensure that the default `switchres.ini` file is loaded only if a core override .ini file was loaded for the previous core

I noticed an issue with this code: https://github.com/alphanu1/MME_SR2/blob/5abd0d92b647a6598f71017eecb13df6f7e14b07/gfx/video_crt_switch.c#L351

For some reason, if you have content running and launch content for a different core without closing the running content explicitly first, then this call does `not` return true. The effects for this on the new functionality is that core overrides are not properly loaded/unloaded between cores in this particular instance. It almost feels like `p_switch->core_name` gets updated elsewhere, but that makes no sense. I'd appreciate if this issue was looked into when/if possible.

**Comment by Kopert** [comment]
Moved the declaration of `crt_adjust_sr_ini` from the .h to the .c as a `static`.

The issue reported previously is a matter of comparing the pointers instead of their values. It would need to be replaced with `strcmp` for the comparison and `strcpy` for the attribution. I'll leave that for another dev to fix as I'm not to change the format of the variable (from `char*`) and I don't think I should be managing `mallocs` in this code just yet.

Edit: I have a patch for this bug that does a single `malloc` and `free`'s it on `crt_destroy_modes`, on my tests it works and only allocates/de-allocates once. I have not added that patch to this PR. Let me know if you want me to.

Edit 2: the fix is now included in this PR.

**Comment by substring** [comment]
Regarding the switchres part, did you edit the switchres code in  deps/switchres or used git subtree ?

**Comment by Kopert** [comment]
> Regarding the switchres part, did you edit the switchres code in deps/switchres or used git subtree ?

I'm sorry, I just copied the changed files over from the switchres repo. Was that wrong?

**Comment by substring** [comment]
yup :) to keep  deps/switchres in sync'ed with the upstream switchres, we use the git subtree feature (as decided by the retroarch team). If you're not familiar with it, just let Alphanu update the folder on lastest SR commit. So you'll have to remove the changes made in  deps/switchres.

**Comment by Kopert** [comment]
I made another update including support for content directory overrides (still following RA's lead with locations, so, for example, the directory overrides for the `Sega - Game Gear` directory of the `Genesis Plus GX` core would be searched, on Linux, at `~/.config/retroarch/config/Genesis Plus GX/Sega - Game Gear.switchres.ini`.

The justification for this is that some cores - like Genesis Plus GX - can support multiple different systems such as Game Gear, SMS and Sega Genesis, so having separate settings for those is reasonable in several use cases. I still don't see a justification for per-game overrides so I'm not developing that at this time.

Regarding the issue with acquiring the updates to `switchres` using `git subtree` functionality, I discussed this with @substring and apparently doing a `pull --squash` on the subtree is not possible right now, potentially because of previous git commit squashing, and I was unable to acquire the updates via git subtree - Git reports `Can't squash-merge: 'deps/switchres' was never added`. As I don't know how we're fixing this at the moment, the changes to the switchres library files are still included in this PR.

**Comment by Kopert** [comment]
I've added a fix for the pointer comparison/assignment to use strcmp/strcpy instead so core changes are properly detected in all cases.

**Comment by alphanu1** [comment]
Subtree causing nothing but issues. even when squash, trying to rebase libretto master caused git merges between SR and RA. Twinphex and my self discuss this and have decided to re move the subtree and just have the source in the deps folder.

@Kopert RA is compiled in a C89 environment, c++ comments will not work. Please can you change all your c++ comments so they are compile-able on C89 /* */

**Comment by Kopert** [comment]
> RA is compiled in a C89 environment, c++ comments will not work. Please can you change all your c++ comments so they are compile-able on C89 /* */

I had no idea this was a thing, thanks for pointing it out. I've pushed a fix.

**Comment by Kopert** [comment]
Fix for an issue where content directory overrides would not be loaded if the core did not change (e.g., core is already loaded, THEN the content is loaded). Also fixed some C89 compatibility issues.

**Comment by Kopert** [comment]
The loading of overrides was moved to a different method, since it wasn't being called before the very first resolution change... which caused overrides to not be used if content was loaded directly from the command line.

**Comment by alphanu1** [comment]
PR raised in Libretro/retroarch git

**Pull request closed without merging**
